### ISSUE TITLE
Validator not recognizing MapUnit in DMU and throwing subsequent errors

### ISSUE THREAD

**Issue by MnashUSGS** [DOI-USGS/gems-tools-pro#45]
I've been running the validator script on a .gdb containing a DescriptionOfMapUnits nonspatial table and MapUnitPolys feature class. 
For example, in MapUnitPolys, unit "gn" is in the MapUnit field. In the accompanying DMU table, "gn" is also entered in the MapUnit field and all relevant information to "gn" is filled out in the other DMU fields.

Despite this, the Validator throws the "MapUnits missing from DMU" error. 
This is occurring for all MapUnits I have in my .gdb for this project, and I'm not sure what the issue is. There are no errant spaces in MapUnit, nor in the DMU. It simply appears the Validator isn't properly reading the DMU.

I've tried restarting both ArcPro and my computer, and it worked only once where it did not throw this error. All subsequent times, the Validator has thrown this error despite it being plainly obvious the DMU is populated with MapUnit(s).
If it's at all relevant, this project and its files are all on OneDrive, but OneDrive syncing is paused while I work on the project. 
Attached image below, showing "gn" being populated in both MUP and DMU, but Validator run throwing an issue:

![GeMSValidatorDMUIssue](https://user-images.githubusercontent.com/99765778/234657263-6d31fe1e-4b93-4baa-9bfb-b19667bb4f44.png)

**Comment by ethoms-usgs** [comment]
Hi Morgan,
First, if you have a map open, check to make sure there are no layers that have the same names but either don't reference the same data source or have definition or selection queries that filter columns or rows in anyway.

If that is not the case, then I suspect it may be due to using OneDrive. Can you try it on a local copy? Or is that the case already? I haven't worked with data on OneDrive yet. Apparently, I need to check that out.

--
​​Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage, AK 99508

________________________________
From: Morgan Nasholds ***@***.***>
Sent: Wednesday, April 26, 2023 9:37 AM
To: DOI-USGS/gems-tools-pro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [DOI-USGS/gems-tools-pro] Validator not recognizing MapUnit in DMU and throwing subsequent errors (Issue #45)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I've been running the validator script on a .gdb containing a DescriptionOfMapUnits nonspatial table and MapUnitPolys feature class.
For example, in MapUnitPolys, unit "gn" is in the MapUnit field. In the accompanying DMU table, "gn" is also entered in the MapUnit field and all relevant information to "gn" is filled out in the other DMU fields.

Despite this, the Validator throws the "MapUnits missing from DMU" error.
This is occurring for all MapUnits I have in my .gdb for this project, and I'm not sure what the issue is. There are no errant spaces in MapUnit, nor in the DMU. It simply appears the Validator isn't properly reading the DMU.

I've tried restarting both ArcPro and my computer, and it worked only once where it did not throw this error. All subsequent times, the Validator has thrown this error despite it being plainly obvious the DMU is populated with MapUnit(s).
If it's at all relevant, this project and its files are all on OneDrive, but OneDrive syncing is paused while I work on the project.
Attached image below, showing "gn" being populated in both MUP and DMU, but Validator run throwing an issue:

[GeMSValidatorDMUIssue]<https://user-images.githubusercontent.com/99765778/234657263-6d31fe1e-4b93-4baa-9bfb-b19667bb4f44.png>

**Comment by MnashUSGS** [comment]
I just confirmed OneDrive is not the issue - I ran the validator script on a new project with a copy of the .gdb and the validator ran fine. 
You can resolve this issue, as I just discovered the nonspatial tables I had in the .gdb for the Validator runs were older copies that I thought I was changing, but in fact were the wrong ones. Rookie mistake, but happens to all of us occasionally... Sorry about that. At least you know it works fine with OneDrive!
