### ISSUE TITLE
Format change in myAttribDict in new my_definitions.py

### ISSUE THREAD

**Issue by alwunder** [DOI-USGS/gems-tools-pro#66]
I am updating my entries in the new my_definitions.py file and noticed that the format of the items in the `myAttribDict` section has been changed from the old my_GeMSDefinitions.py.  I looked at the old and new GeMS_Definition.py and noted that the `attribDict` and `entityDict` format has not changed, aside from the change from single quotes to double quotes.

In the `myAttribDict` section of the new my_definitions.py there is an additional item ("foobar") at the end of each entry, with the last two parts now also placed within brackets:
    `"Significance": ["Brief discussion of significance of reported age.", "foobar"],`
What is the additional bit for?  And why the change to `myAttribDict` but not `myEntityDict`?

Also, I have double quotes `""` within some of my definitions and the change to double quotes to surround the definitions may be problematic (e.g., `'Term':'Defined as "this", and other things'`).  I think I may have to use escape character (`\"`) or perhaps triple quotes (`"""definition"""`) around my definitions to make them behave?

**Comment by ethoms-usgs** [comment]
Right, concerning `myAttribDict`, the change there is so that you can store an entry for the source. With the previous 3 step metadata-building process, the dictionaries in my_GeMSDefinitions would be located automatically and added to `attribDict` and `entityDict`, and the source for the latter two (GeMS) is known to the tool, so that would get added. But no source would be added for the custom definitions. 

In fact, there was a similar change made to `entityDict` but you are looking at the wrong my_definitions.py file! Sorry. The one in Scripts needs to be removed. Look at the one in Resources.

The change in quotes is coming from VS Code enforcing [Black](https://pypi.org/project/black/) formatting. 
You shouldn't have to use an escape character to save double quotes on substrings in a single-quote enclosed string. That should print fine but let me know.

**Comment by alwunder** [comment]
Ah! Thank you for the clarification! I see the correct my_definitions.py file and have updated my custom attribute and entity lists accordingly.  I will test the Validate database tool again as well as the Metadata tool and see how it goes.
