### ISSUE TITLE
Build Metadata tool issue (2.12.9): Bounding coordinates written to xml are way off...

### ISSUE THREAD

**Issue by alwunder** [DOI-USGS/gems-tools-pro#92]
I am reproducing metadata for re-submission of GeMS packages using the new Build Metadata tool. With the old metadata tool, I would export a shapefile of the DataSourcePolys class and import the spatial information from it to the xml using Metadata Wizard. The bounding coordinates were always really close and required only a small adjustment to get them set to the exact quadrangle bounding lat/lon. See screenshot:

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/a5b2f5ef-8716-47df-8b1f-808c25a5e3ba)

When I run the Pro Build Metadata tool on the same geodatabase, I get coordinates that are *way* off. I have looked at the extents of the individual feature classes within the database and they are all within reason, and the zoom to full extent tool in ArcGIS Pro zooms to the layers normally.

See the screenshot for an example of the extent I am getting for the same geodatabase as above:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/9ef447ff-0865-45c3-b648-05db0bb1a923)

I am still trying to track down the issue, but I thought I'd see if anyone else was having the same problem. Thoughts?

**Comment by ethoms-usgs** [comment]
That's interesting. The bounding box built by the tool uses Metadata Wizard code, although MW only shows the extent of one feature class at a time, whereas the tool finds the maximum extent of all features in the gdb.

From MetadataWizard\fort-pymdwizard\pymdwizard\gui\spatial_tab.py:

```
def populate_from_fname(self, fname):
    msg = ""
    try:
        spdom = spatial_utils.get_bounding(fname)
        self.spdom.from_xml(spdom)
    except:
        msg = "Problem encountered extracting bounding coordinates"
        self.spdom.clear_widget()
```

where fname is the open file. I simply call spatial_utils.get_bounding() for each feature class and then find the max and min

```
def max_bounding(db_path):
    north = []
    south = []
    west = []
    east = []
    for layer in ogr.Open(db_path):
        if layer.GetGeomType() != 100:
            # if "MapUnitPolys" in layer.GetName() or "ContactsAndFaults" in layer.GetName():
            bounding = su.get_bounding(str(db_path), layer.GetName())
            north.append(bounding.find("northbc").text)
            south.append(bounding.find("southbc").text)
            west.append(bounding.find("westbc").text)
            east.append(bounding.find("eastbc").text)

    bounding.find("northbc").text = max(north)
    bounding.find("southbc").text = min(south)
    bounding.find("westbc").text = max(west)
    bounding.find("eastbc").text = min(east)

    return bounding
```
What is going wrong there?

**Comment by alwunder** [comment]
Evan, forgive me, but I really went down the rabbit hole on this one... 

I decided to go over the Describe Database report again to see if there was something I missed. I put the report in Excel, reformatted it a bit so it would play nice with the filtering, and looked again at the extent numbers.  They all jive perfectly with the GeologicMap feature dataset describing the maximum extent (in projected units) of the features on the map!

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/55a4af2f-cf73-41e7-9262-de4b430681df)

Then I looked at the other items in the report and this caught my attention:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/b07ceb8f-834b-45bd-9d45-58e8a66b4c62)

The feature datasets (CartographicElements and GeologicMap) have projections defined and they are the same. But look at the classes contained within them.  Some show a different projection definition! They are actually the same projection but in units of meters instead of feet. So I passed those coordinates (which are in feet) to the NGS coordinate converter as METERS:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/9ef1b1dd-7925-427a-978e-a195c8d4e79b)
Guess what happens? 39N 81W...

**Comment by ethoms-usgs** [comment]
Ok, my head is spinning a bit, but the first thing that jumps out is that I thought feature classes HAD to have the same SR as the feature dataset they were in. Not fair! I wonder how that happens.

Still, that point is moot concerning that spatial_utils.get_bounding() only considers OGR layers. I do need to add some code to exclude feature classes in datasets like CartographicElements and any others that have 'Unknown' spatial references, but for now we can ignore the spatial reference of the feature dataset itself.

I investigated a bit with a Jupyter Notebook. I took a TN database I have (Bellwood) and looked at the extent of ContactsAndFaults. Here's what drawing a box defined by the extent and the actual features and looked like this:

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/5376315/6065f7bc-766e-45f1-a6d4-5b512ffec5dc)

The extent box (gray) is obviously off. It turns out the feature class extent is a property that is not always updated when features are edited. You need to run the [Recalculate Feature Class Extent](https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/recalculate-feature-class-extent.htm) tool. After doing that, the extent box looks perfect:

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/5376315/432d7947-eccb-461f-b121-35e3896f1ba2)

I don't know if this is causing your crazy extents or not. Exporting a feature class to a shapefile must result in a new extent, so that could explain how MW shows a good extent in that case. Have to check out a few more examples.

**Comment by alwunder** [comment]
I guess what I still don't get is that the arcpy.da.describe extents are correct in projected units and when I pass those to the NGS coordinate converter I get the correct corresponding lat/lon.  What is the OGR layer extent returning?  The max the extent of the feature class ever was?  If that's the case, I can tell you why it's happening in the Bellwood example you have above: I ran topology on a six-quad band that Bellwood was the westernmost of.  That rectangle you got the first time is the extent of the entire set of six quads.  Each quad then had it's ContactsAndFaults and MapUnitPolys sent to their respective databases, but the "extent" of the whole thing must have gotten transferred somehow.

I looked at the OGR layer .GetExtent documentation and it doesn't really shed any light on the logic of what it is reading, however, the fact that you can "force" the tool to recalculate the extent "expensively" means to me that it is understood that the extent returned may not match the actual extent of the features *currently* in the layer. 

I seem to recall back in the ArcGIS 9.x days that I had a little VBA macro button that I used to update the extents of feature classes and shapefiles that didn't behave when "zooming to layer" in ArcMap.  For some reason, I thought this was not a problem in file geodatabases, but I guess it still is.

I will try two things. First I will use my "copy to new database" script to append all the classes in the offending gdb into a fresh copy of the GeMS schema that I know is defined correctly. The append should force the extent to be recalculated?  We'll see.  Second, I will make a little "update extent" script and see if that has any effect on the offending Bonicord database I was using as an example above.  That one may still be problematic if that weird projection issue causes the MW extent tool to pass the coordinates to be converted in the wrong units.

Thanks for taking a look at this, Evan. I'll report back when I have done more testing.

**Comment by alwunder** [comment]
My research on this weird extent problem yielded two results: The first is that even after updating the extents of the feature classes in the original database with the strange projection definitions, Build Metadata provided incorrect results for the extent (as predicted) because the MW script is passing the projected coordinates in the wrong units for the north and east extent:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/73252bfe-f073-48d8-8384-569add357f9c)

The second test was to append the datasets from the messed up db to a fresh, empty copy of a TNGeMS db with known good projection definition.  It turns out that running the append tool DOES NOT update/recalculate the extent of the feature class, which is strange to me, but proven by the results for the extent found by the MW tool:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/86544efd-f6e9-43b7-8f4f-9114222f4046)

So, I put together a little script to update the extents of all the feature classes in a database (see Discussion section for code) and ran it on the known good projected db and voila:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/89945503/6d2a857d-de9f-43fe-8e0a-ceb90393d801)

These are the correct/desired results!  As expected, the numbers are just a tiny bit off due to the coordinate conversion, but the bounding box is correct.

Moral of the story: I will now be running the "Recalculate FC Extents" tool as part of my workflow to clean up my GeMS dbs before running the Build Metadata tool.

**Comment by ethoms-usgs** [comment]
In your last gdb, with "known good projection definitions", are the units in feet or meters? I am finding that when I calculate a bounding box using the spatial_utils code, that it deals with feet as expected. 

I am pretty sure that for a given feature class or dataset, that both arcpy and ogr are pulling the extent information that is stored in the 'Definition' field of the system table 'GDB_Items'. As we have learned, those values are only updated occasionally or explicitly. 

I think in the case of the gdb with mis-matched SRs, that all of the calculations are being done correctly on the feature classes themselves but that GeologicMap, although defined with feet, has the extent coordinates in meters because that's what the children feature classes use.

Note that when you ran max_bounding() with 

`if "MapUnitPolys" in layer.GetName() or "ContactsAndFaults" in layer.GetName():` 

as opposed to looking at all feature classes, you still got three sets of coordinates because of 'GMMapUnitPolysAnno'. Could that have been the cause of the some of the large extent rectangles? That the extent of that fc wasn't recalculated until you ran your script over the entire gdb?

Are we good at this point as long we know that the SR of the feature dataset matches the children and extents have been recalculated?

**Comment by ethoms-usgs** [comment]
Ok, great.
I will probably add recalculate extent to the metadata tool as well.
